# Generated by Django 5.0.7 on 2024-07-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='extracted_text',
        ),
    ]
